using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace UnitySwaggerGenerator
{
    public static class DTOGenerator
    {
        public static string ToPascalCase(string input)
        {
            if (string.IsNullOrEmpty(input)) return input;

            string[] words = input.Split(new[] { '_', '-', ' ' }, StringSplitOptions.RemoveEmptyEntries);
            for (int i = 0; i < words.Length; i++)
            {
                string w = words[i];
                if (w.Length > 0)
                {
                    words[i] = char.ToUpper(w[0]) + w.Substring(1);
                }
            }
            string result = string.Concat(words);

            if (result.Length > 0)
            {
                result = char.ToUpper(result[0]) + result.Substring(1);
            }

            return result;
        }

        public static string MapType(string rawType, string format, string refPath)
        {
            if (!string.IsNullOrEmpty(refPath))
            {
                return ToPascalCase(SwaggerParser.ExtractClassNameFromRef(refPath));
            }

            switch (rawType)
            {
                case "string":
                    return "string";
                case "integer":
                    if (format == "int64") return "long";
                    return "int";
                case "boolean":
                    return "bool";
                case "number":
                    if (format == "double") return "double";
                    if (format == "decimal") return "decimal";
                    return "float";
                default:
                    return "object";
            }
        }

        public static string GetCSharpType(ParsedProperty property)
        {
            if (property.IsArray)
            {
                string itemType = "object";
                if (!string.IsNullOrEmpty(property.ArrayItemsRefPath))
                {
                    itemType = ToPascalCase(SwaggerParser.ExtractClassNameFromRef(property.ArrayItemsRefPath));
                }
                else if (!string.IsNullOrEmpty(property.ArrayItemsType))
                {
                    itemType = MapType(property.ArrayItemsType, property.ArrayItemsFormat, null);
                }
                return $"List<{itemType}>";
            }

            return MapType(property.RawType, property.Format, property.RefPath);
        }

        public static void Generate(List<ParsedSchema> schemas, string outputFolder, string namespaceName = "UnitySwaggerGenerator.DTOs")
        {
            if (string.IsNullOrEmpty(outputFolder)) return;

            if (!Directory.Exists(outputFolder))
            {
                Directory.CreateDirectory(outputFolder);
            }

            foreach (var schema in schemas)
            {
                string className = ToPascalCase(schema.Name);
                var sb = new StringBuilder();

                sb.AppendLine("//------------------------------------------------------------------------------");
                sb.AppendLine("// <auto-generated>");
                sb.AppendLine("//     This code was generated by Unity Swagger DTO Generator.");
                sb.AppendLine("// </auto-generated>");
                sb.AppendLine("//------------------------------------------------------------------------------");
                sb.AppendLine();
                sb.AppendLine("using System;");
                sb.AppendLine("using System.Collections.Generic;");
                sb.AppendLine("using Newtonsoft.Json;");
                sb.AppendLine();
                sb.AppendLine($"namespace {namespaceName}");
                sb.AppendLine("{");
                sb.AppendLine($"    public class {className}");
                sb.AppendLine("    {");

                foreach (var prop in schema.Properties)
                {
                    string csharpType = GetCSharpType(prop);
                    string cleanPropName = ToPascalCase(prop.Name);

                    if (cleanPropName == className)
                    {
                        cleanPropName += "Value";
                    }

                    sb.AppendLine($"        [JsonProperty(\"{prop.Name}\")]");
                    sb.AppendLine($"        public {csharpType} {cleanPropName} {{ get; set; }}");
                    sb.AppendLine();
                }

                sb.AppendLine("    }");
                sb.AppendLine("}");

                string filePath = Path.Combine(outputFolder, $"{className}.cs");
                File.WriteAllText(filePath, sb.ToString(), Encoding.UTF8);
            }
        }
    }
}
